image: mcr.microsoft.com/dotnet/sdk:9.0

variables:
  MAIN_BRANCH: "main"

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.latest.gitlab-ci.yml

stages:
  - restore
  - build
  - test
  - sast
  - dependency_scanning

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - when: never
    - when: manual

restore:
  stage: restore
  tags:
    - windows
  script:
    - dotnet restore ASPWebApi.slnx

build:
  stage: build
  tags:
    - windows
  script:
    - dotnet build ASPWebApi.slnx --no-restore

test:
  stage: test
  tags:
    - windows
  script:
    - dotnet test WebApiTests/WebApiTests.csproj --no-build

dependency_scanning:
  stage: dependency_scanning
  tags:
    - windows
  script:
    - dotnet list ASPWebApi.slnx package --vulnerable

custom_sast:
  stage: sast
  tags:
    - windows
  image: returntocorp/semgrep:latest
  script:
    - semgrep scan --config auto --json --output gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
    when: always
  allow_failure: true